# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: myproto.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rmyproto.proto\"%\n\tIdMessage\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0c\n\x04hash\x18\x02 \x01(\t\"K\n\tMyRequest\x12\x0f\n\x07\x63ontent\x18\x05 \x03(\t\x12\x1e\n\nid_request\x18\x01 \x01(\x0b\x32\n.IdMessage\x12\r\n\x05\x63ount\x18\x02 \x01(\x05\">\n\nMyResponse\x12\x1f\n\x0bid_response\x18\x01 \x01(\x0b\x32\n.IdMessage\x12\x0f\n\x07\x63ontent\x18\x05 \x03(\t25\n\x0bTodoService\x12&\n\x0bSendMessage\x12\n.MyRequest\x1a\x0b.MyResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'myproto_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _globals['_IDMESSAGE']._serialized_start=17
  _globals['_IDMESSAGE']._serialized_end=54
  _globals['_MYREQUEST']._serialized_start=56
  _globals['_MYREQUEST']._serialized_end=131
  _globals['_MYRESPONSE']._serialized_start=133
  _globals['_MYRESPONSE']._serialized_end=195
  _globals['_TODOSERVICE']._serialized_start=197
  _globals['_TODOSERVICE']._serialized_end=250
# @@protoc_insertion_point(module_scope)
