name: Build and Push Docker Image

on:
  push:
    branches:
      - hw11

jobs:
  linter: 
    runs-on: ubuntu-latest
    steps:
        - name: Checkout code 
          uses: actions/checkout@v4
                
        - name: Set up Python
          uses: actions/setup-python@v3
          with:
            python-version: 3.8
        
        - name: Install dependencies
          run: |
            pip install --upgrade pip
            pip install -r hw10/producer/requirements.txt

        - name: Run linter
          run: |
            pip install pylint
            pylint hw10/producer/producer.py


  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - uses: docker/build-push-action@v2
        with:
            file: hw11/Dockerfile
            context: .
            push: true
            tags: hw11:latest